### ISSUE TITLE
Why is this happneing

### ISSUE THREAD

**Issue by nardius** [Fenixin/Minecraft-Region-Fixer#109]
everytime i put in a command cmd says its not recognized as internal or external command. why? Tell me if you see anything wrong in this picture

![bullshit](https://user-images.githubusercontent.com/63264953/78607326-d7a48900-782c-11ea-8566-1a4b96e38d9b.PNG)

**Comment by Fenixin** [comment]
Hello!

Give this pages a look: 
https://github.com/Fenixin/Minecraft-Region-Fixer/wiki/Installation
https://github.com/Fenixin/Minecraft-Region-Fixer/wiki/Usage

And see if that solves the problem. Don't hesitate to ask if you have more problems

**Comment by EvilSupahFly** [comment]
First, be sure you've installed Python 3, as instructed in the links above, then use `python3 regionfixer.py` instead of `python regionfixer.py` when running Fixer.

Also, since both Windows and Python can be particular about spaces in pathnames, be sure you've enclosed the whole path pointer to your world in double quotes:

`python3 regionfixer.py -p 4 "C:\Users\shade\Desktop\minecraft servers\bteam\world"`

**Alternatively**, copy all the Fixer stuff to your `Minecraft Servers` folder so you shorten it to:
 `python3 regionfixer.py -p 4 ./bteam/world` 

**Or** replace the _space_ (` `) with an _underscore_ (`_`) or _dash_ (`-`), changing the pathname from 

`C:\Users\shade\Desktop\minecraft servers\bteam\world`

To either

`C:\Users\shade\Desktop\minecraft_servers\bteam\world' or `C:\Users\shade\Desktop\minecraft-servers\bteam\world`

**Comment by EvilSupahFly** [comment]
First, be sure you've installed Python 3, as instructed in the links above, then use `python3 regionfixer.py` instead of `python regionfixer.py` when running Fixer.

Also, since both Windows and Python can be particular about spaces in pathnames, be sure you've enclosed the whole path pointer to your world in double quotes:

`python3 regionfixer.py -p 4 "C:\Users\shade\Desktop\minecraft servers\bteam\world"`

**Alternatively**, copy all the Fixer stuff to your `Minecraft Servers` folder so you can shorten the program launch to:
 `python3 regionfixer.py -p 4 ./bteam/world` 

**Or** rename the `minecraft servers` folder by replacing the _space_ (` `) with an _underscore_ (`_`) or _dash_ (`-`) like so:

`C:\Users\shade\Desktop\minecraft servers\bteam\world`

To either

`C:\Users\shade\Desktop\minecraft_servers\bteam\world` or `C:\Users\shade\Desktop\minecraft-servers\bteam\world`

**Comment by Fenixin** [comment]
So this seems to be a problem of usage and installation (and pretty outdated wiki). Don't hesitate to open a new issue if you need more help, or to reopen this one.

Also, @EvilSupahFly, thanks for your help!

**Comment by EvilSupahFly** [comment]
I'm always happy to lend a hand where I can. 🙂
