### ISSUE TITLE
Bug report: 1.16.1 server

### ISSUE THREAD

**Issue by asifkhan123** [Fenixin/Minecraft-Region-Fixer#124]
I got the following bug  , I was trying to fix my corrupted world and the software keeps showing me this bug report. I did it through cmd and ran it with administrator , I did every step right to use the regionfixer but it is still asking me to send this bug report to you guys , so are there any solutions for this ?

**
 Exception while scanning:
 r.-7.-3.mca
**
 Printing the child's traceback:
 Exception:<type 'exceptions.ValueError'>Unrecognised tag type
**
 File regionfixer_core\scan.pyo, line 694, in scan_region_file
   None**
 File regionfixer_core\scan.pyo, line 778, in scan_chunk
   None**
 File nbt\region.pyo, line 567, in get_chunk
   None**
 File nbt\region.pyo, line 552, in get_nbt
   None**
 File nbt\nbt.pyo, line 517, in init
   None**
 File nbt\nbt.pyo, line 544, in parse_file
   None**
 File nbt\nbt.pyo, line 391, in _parse_buffer
   None**
 File nbt\nbt.pyo, line 379, in init
   None**
 File nbt\nbt.pyo, line 391, in _parse_buffer
   None**
 File nbt\nbt.pyo, line 379, in init
   None**
 File nbt\nbt.pyo, line 395, in _parse_buffer
   None
**

**Comment by Fenixin** [comment]
Hello!

In order to help you I need some information. As it is written in the template of bug report the next information would be very useful: 

**Where did you download regionfixer**
From github or any other place? 

**Describe the bug**
A clear and concise description of what the bug is.

**Full copied text from the MS-DOS view**
Please, include the command used to run regionfixer.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Files that would help solving the issue**
If possible, the world/files that triggers the error.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Python version: [e.g. 2.7]
 - Region Fixer Version [e.g. 2.0.1]

**Additional context**
Add any other context about the problem here.

**Comment by Fenixin** [comment]
Closing this. Feel free to open a new issue if you need help.
