### ISSUE TITLE
Request for a version of --fix-wrong-located with the opposite behavior

### ISSUE THREAD

**Issue by shockculture** [Fenixin/Minecraft-Region-Fixer#146]
Would it be possible to add a function similar to --fix-wrong-located, but instead of moving the chunks by saving them to the coordinates stored in their internal data, to instead update their internal data to match the .mca filename they are found in?

The reason for this request is that I have a large map that I moved east and south by two .mca grid spaces, and Spiggot has fixed many of the wrongly located chunks by updating their internal coordinate data. However, it fails when there are entities in those chunks, or when there are too many for it to keep up with. 

As a workaround, I have also tried removing all of the entities using Minecraft-Region-Fixer, using -de with a -el of 0, but some sheep, chickens, and torches continued to remain, even after multiple passes.

**Comment by Fenixin** [comment]
Hello!

Thanks for the well written and ordered request.

> Would it be possible to add a function similar to --fix-wrong-located, but instead of moving the chunks by saving them to the coordinates stored in their internal data, to instead update their internal data to match the .mca filename they are found in?

I think it's possible but I don't have that much free time and I don't think this is going to be used by a lot of people, so this won't be added by me. Feel free to add it yourself! But, if you want some advice from a hobbyist coder, do this in a separate script, should be easier than adding to other program.

> As a workaround, I have also tried removing all of the entities using Minecraft-Region-Fixer, using -de with a -el of 0, but some sheep, chickens, and torches continued to remain, even after multiple passes.

If I recall correctly there are entities and block entities. Regionfixer only looks in the pure entities (mobs, dropped items, etc) but it doesn't check for block entities (for example chests). I'm saying this from memory, so I might be completely wrong and things might have changed since I coded this. That said, it's normal that regionfixer is not removing torches (they are a block with ancillary data), but sheep and chickens should be removed, so, something strange is going on there. Could you check that this is really a problem?

**Comment by Fenixin** [comment]
The last part of your bug report could be partly fixed by one of the latest pull request. So I'm closing this. Feel free to reopen for the feature request.
