### ISSUE TITLE
Says chunks aren't corrupted but when I join my mc world, they still are

### ISSUE THREAD

**Issue by bunniesrolls** [Fenixin/Minecraft-Region-Fixer#160]
my mc world recently got corrupted, so I figured to give this a try. But, it scanned and says it isn't corrupted.

**Comment by Fenixin** [comment]
Hello!

Sorry for the late answer. If you want some help I need some more information. You could use the bug report template. I'm pasting it here:

**Describe the bug**
A clear and concise description of what the bug is.

**Full copied text from the MS-DOS view**
Please, include the command used to run regionfixer.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Files that would help solving the issue**
If possible, the world/files that triggers the error.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Python version: [e.g. 2.7]
 - Region Fixer Version [e.g. 2.0.1]

**Additional context**
Add any other context about the problem here.

**Comment by Fenixin** [comment]
I'm closing this, feel free to reopen it if you need.
