### ISSUE TITLE
Cleaning entities causes crashes all over the world.

### ISSUE THREAD

**Issue by andrewkm** [Fenixin/Minecraft-Region-Fixer#52]
@Fenixin 

Have a massive 60GB world of 6 years.
Just tried clearing all entities, and getting serious crashing all over:

http://pastie.org/pastes/10973115/text?key=h1fsl9iuzjntavf2vtcha

In various sections and areas.
Assuming Region Fixer is simply out of date for old maps and 1.10.2 spigot/etc?

**Comment by Fenixin** [comment]
Hello!

I haven't update region fixer in a long time and I can't find any recent changes to the world format, so I don't know what's wrong with your world. Any mods that changes the world format?

**Comment by andrewkm** [comment]
No my world has nothing changed via mods.
The entity cleaning is simply broken with Region-Fixer :( which really is a shame. It's a huge 40GB world on a server that's been running for 6 years.

**Comment by macfreek** [comment]
(sorry for the late reply, I happened to saw the reply in my notifications, but missed the original question)

From what I read at the pastie, it seems that Spigot is complaining that two chunks can't be loaded, and two strings are incorrect UTF.

That sounds like two rather low-level errors. I.e. your world is (partially) corrupt.

Does Spigot give these errors with the original world, or only with the world after you cleared its entities? If it is only the later, it would seem that Minecraft-Region-Fixer (or the underlying NBT library) somehow mangled your data. That would be bad, and certainly worth a bug report.

If it is the later case, I suggest to continue with your original world, until the bug in Minecraft-Region-Fixer is fixed (in that case, it certainly helps to get a more detailed report).

If the bugs where already there before you started to use Minecraft-Region-Fixer, I would do the following:

1. To start with, are these the only 4 errors you've got? If so, I would try to recover those regions (or even just the chunks) from a backup (assuming you have backups), and just continue.

2. If you don't have backups, my second attempt would be to determine to what extend the files are really corrupt. Have you tried reading the world with another program. Perhaps a non-Spigot server, or indeed with Minecraft-Region-Fixer (which uses the underlying NBT library). Do these programs report the same errors? If not, make sure it reads all chunks and all data (e.g. do some thorough check). If still not, it might be that the bug is in Spigot, not your world data.

**Comment by andrewkm** [comment]
"Does Spigot give these errors with the original world"
- No

"If it is the later case, I suggest to continue with your original world, until the bug in Minecraft-Region-Fixer is fixed"
- Yes our original world before the entity cleaning works perfectly fine. Region fixer also detects no bad/corrupted chunks.

It's almost certainly a bug with region fixers entity cleanup.

**Comment by andrewkm** [comment]
Found a way around this. Thanks for the help.

**Comment by Fenixin** [comment]
@andrewkm, sorry for the lack of work by my part. Could you explain a little more how did you workaround this? What did the plugin do?
