### ISSUE TITLE
/

### ISSUE THREAD

**Issue by AhNuCheekiBreeki** [Fenixin/Minecraft-Region-Fixer#92]

**Comment by Fenixin** [comment]
Hello!

In order to help you I would need some more information:

What operative system are you using?
What verison of python are you using?
What command are you using to run regionfixer?

**Comment by AhNuCheekiBreeki** [comment]
Win 10 and Python 3.7.4
https://i.imgur.com/ojN4e2D.png

**Comment by Fenixin** [comment]
I have uploaded a new branch called [fixes](https://github.com/Fenixin/Minecraft-Region-Fixer/tree/fixes). Could you please try it and see if it fixes your problem?

Also, please, note that in order to use directories with spaces and special characters in Windows you have to write the folder address between quotation marks, for example:

`regionfixer.py "c:\Users\my name\Documents\First server ever"`

**Comment by Fenixin** [comment]
I don't know what's going on, I'm just scanning and testing that same version and it works perfectly.

I'm really sorry but I have no idea what's happening. Are you in a special version of windows? Is your system special in any way? Is python installed in a strange way? Any clue?

I'm really looking the code and your inputs and I really don't know what's going on.

**Comment by AhNuCheekiBreeki** [comment]
I really don’t know either. If your version is working can you scan my corrupted world and regenerate the corrupted chunks? It has been killing me and it is why I have been trying this. It would make me very happy

**Comment by Fenixin** [comment]
Yes. Just send me your world and I'll scan it for you and send it back. I don't know if the problems you are having are going to be fixable by regionfixer but if that is the case I will fix it.

You can post here a link, send me a PM to git or a email to my user account at gmail dot com.

**Comment by Fenixin** [comment]
Got your world but the scan says it has nothing wrong. I've just attached two files with all the info that regionfixer returns. But as I have said there is no problem.

[Scan verbose.txt](https://github.com/Fenixin/Minecraft-Region-Fixer/files/3637381/Scan.verbose.txt)
[Scan short.txt](https://github.com/Fenixin/Minecraft-Region-Fixer/files/3637382/Scan.short.txt)

Could you tell me what are the symptoms that make you think that your world is corrupted? Maybe I can help you. It's very strange that regionfixer doesn't work on your systema and also that the world is giving you problems.

**Comment by Fenixin** [comment]
Ok... so it seems that I can't read. Your idcounts.dat is broken, not too much to do with that, you could remove it.

Also there are things that regionfixer doesn't scan right now. I probably should update that too. I think I'll leave this open as a reminder.

**Comment by AhNuCheekiBreeki** [comment]
At my 0,0 where the seed should have generated a plains biome it is a newly generated deep ocean spanning the entire half of my world. Going over 100 blocks from my house I see chunk errors, like Jungle growing next to an extreme hills biome 50 blocks taller than it on the chunk border, everywhere. Doing a fresh start from an old save in an older version changes where the deep ocean starts.

**Comment by Fenixin** [comment]
Ok, I'm going to theorize here a little bit, juts to try to shed some light in this issue and try to help you. I would say that you had a really bad case of world corruption. With that a lot of your world got broken, maybe even the level.dat file (where the seed of your world is stored)

After that Minecraft detected some problems and removed those chunks and regenerated them. They are not the same type of terrain because: 
* Maybe the level.dat got corrupted and Minecraft regenerated it, loosing the original seed of the world and hence changing the world.
* Maybe the world generation code changed since you started the world. I don't really follow the development of Minecraft anymore but I know that they change the generation code frequently.

All this to just say that if the world has been regenerated by Minecraft then there is nothing fix with regionfixer. The world is "not corrupted" you may have lost a lot but nothing is wrong from the world format point of view and regionfixer can't help you (and neither can I).

The only thing that would help you in a case like this is a backup.

I don't know if I can help you in any way if you think so just ask.

**Comment by AhNuCheekiBreeki** [comment]
I’m afraid that’s probably what it is, I’ve had this world for 5 years and although they have made it better over the years corruptions were really bad a while ago. The seed I have shows it should be forest where the ocean is so I don’t really know
